# Configuration for BetterSniffer plugin
Disable : false # Disable the plugin functionality, the plugin will no longer add the "drops" to the sniffer loot table
OverwriteVanilla : false # The sniffer will never drop the vanilla items ( seeds, bones, rotten flesh, etc. ) and will only drop the custom items configured in the plugin
# To create a new drop, run the command /bettersniffer create <name> <chance> <biomes>
# Hold the item you want to drop in your main hand and run the command
# Example: /bettersniffer create name 20 PLAINS RIVER DESERT
# This will create a new drop called "name.yml" with a 20% chance to drop in the biomes PLAINS, RIVER, and DESERT
# To view all the drops configurations you have made, look into the folder "drops" in the BetterSniffer directory
# To remove a drop, simply delete the file from the "drops" folder
# Placeholders: - ALL              - All biomes / All worlds
# If you do want to ban specific worlds, add them to the banned_worlds list in the name.yml file
# Example of a name.yml file:
#material: COOKED_BEEF
#item: {}
#chance_of_drop: 20
#biomes: [PLAINS, RIVER, DESERT]
#banned_worlds: [world_nether, world_the_end, wolrd_name, a_very_cool_world]

# That specific item will have a 20% chance to drop in the biomes PLAINS, RIVER, and DESERT, but not in the worlds world_nether, world_the_end, wolrd_name, a_very_cool_world
# Run the command /bettersniffer reload to reload the plugin configuration and apply the changes

# $ PERMISSIONS $ #
# bettersniffer.commands - Allows the player to use all the commands from the plugin
# bettersniffer.reload - Allows the player to reload the plugin configuration
# bettersniffer.create - Allows the player to create a new drop

# $ COMMANDS $ #
# /bettersniffer reload - Reloads the plugin configuration
# /bettersniffer create <name> <chance> <biomes> - Creates a new drop

# Operators have all the permissions by default

# Probabilities Theory
#
# Note that drops with the same criteria( same biome, in a valid world ) will be tested in order displayed in the 'drops' folder
# You should name the files in the 'drops' folder in a way that the order of the drops is the order you want them to be tested
# As an example drop_1_item.yml will be tested before drop_2_item.yml ; use this to your advantage to create a hierarchy of drops, name them accordingly like drop_1_cool_item.yml, drop_2_another_cool_item.yml, etc.
# You can obviously name the files however you want, but it will be easier to manage them .
# The sum of all the chances of the drops that have the same criteria should be equal to 100, they can exceed 100, but the percentage will be calibrated. ( if you do have 6 drops with 20% each, the percentage will be calibrated to 16.66 % ) .
# The sniffer will only dig one block, so the drop will be the first one that meets the criteria, if the sniffer does not find any drop that meets the criteria, it will drop the vanilla items.